# Generated by Django 4.1.7 on 2023-02-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
