# Generated by Django 4.1.7 on 2023-02-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
