# Generated by Django 4.1.7 on 2023-02-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
