# Generated by Django 4.1.7 on 2023-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilecover',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_covers'),
        ),
    ]
